[package]
name = "snips-nlu-ontology-ffi-with-parsers"
version = "0.55.0-SNAPSHOT"
authors = ["Kevin Lefevre <kevin.lefevre@snips.ai>"]

[dependencies]
libc = "0.2"
snips-nlu-ontology = { path = "../snips-nlu-ontology" }
snips-nlu-ontology-ffi-macros = { path = "../snips-nlu-ontology-ffi-macros" }
snips-nlu-ontology-parsers-ffi-macros = { path = "../snips-nlu-ontology-parsers-ffi-macros" }

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]
